name: Build/Push DEV image

on:
  workflow_dispatch:
  push:
    branches: [staging]
    tags:
      - "*.*.*-dev"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: "${{ secrets.DOCKER_USER }}/${{ github.event.repository.name }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            NODE_ENV=development
            VITE_ORGANIZATION_API_URL=${{ secrets.VITE_ORGANIZATION_API_URL || 'https://gerson-organization-api.hackaton.appmoove.com.br' }}
            VITE_PORT=5173

